### ISSUE TITLE
Error Search Brave History

### ISSUE THREAD

**Issue by ThomasBormans** [Acidham/brave-history#1]
The workflow worked perfectly until a few weeks ago. The following error appears in the debug console:
```
[16:04:29.611] Logging Started...
[16:04:32.903] Search Brave History[Script Filter] Queuing argument 'test'
[16:04:33.064] Search Brave History[Script Filter] Script with argv 'test' finished
[16:04:33.067] ERROR: Search Brave History[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.EB59B897-2EDD-4084-8436-7D805EA8C68E/brave_bookmarks.py", line 50, in <module>
    bookmarks = get_all_urls(bm_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.EB59B897-2EDD-4084-8436-7D805EA8C68E/brave_bookmarks.py", line 27, in get_all_urls
    get_container(the_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.EB59B897-2EDD-4084-8436-7D805EA8C68E/brave_bookmarks.py", line 25, in get_container
    extract_data(i)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.EB59B897-2EDD-4084-8436-7D805EA8C68E/brave_bookmarks.py", line 13, in extract_data
    if data['type'] == 'url':
TypeError: string indices must be integers
```
Do you have any idea how I can fix this?

**Comment by Acidham** [comment]
I am not able to reproduce this error but I tried to fix it. Please update to v0.8 and let me know

**Comment by ThomasBormans** [comment]
I have installed 0.0.8 and the error is gone but another one appeared:
```
[13:13:40.003] Search Brave History[Script Filter] Queuing argument 'test'
[13:13:40.123] Search Brave History[Script Filter] Script with argv 'test' finished
[13:13:40.125] ERROR: Search Brave History[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.87BEF024-165F-45D9-A5BC-6D8D3CCFAC5A/brave_bookmarks.py", line 53, in <module>
    bookmarks = get_all_urls(bm_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.87BEF024-165F-45D9-A5BC-6D8D3CCFAC5A/brave_bookmarks.py", line 28, in get_all_urls
    get_container(the_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.87BEF024-165F-45D9-A5BC-6D8D3CCFAC5A/brave_bookmarks.py", line 26, in get_container
    extract_data(i)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.87BEF024-165F-45D9-A5BC-6D8D3CCFAC5A/brave_bookmarks.py", line 14, in extract_data
    if data.get('type') == 'url':
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by Acidham** [comment]
@ThomasBormans please try again if issue is fixed.

**Comment by ThomasBormans** [comment]
0.8.5 gives me the following error:
```
[14:37:33.549] Logging Started...
[14:37:36.350] Search Brave History[Script Filter] Queuing argument 'test'
[14:37:36.534] Search Brave History[Script Filter] Script with argv 'test' finished
[14:37:36.537] ERROR: Search Brave History[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.65C142C6-AFAB-4027-B61A-357E4D624697/brave_bookmarks.py", line 52, in <module>
    bm_json = get_json_from_file(bookmarks_file)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.65C142C6-AFAB-4027-B61A-357E4D624697/brave_bookmarks.py", line 44, in get_json_from_file
    return json.load(bm_file)['roots'].encode('utf-8')
AttributeError: 'dict' object has no attribute 'encode'
```

**Comment by Acidham** [comment]
Yeah got the same error after my fix, sorry! 
Please try again with 0.8.6

**Comment by ThomasBormans** [comment]
Almost the same url as two days ago:
```
[12:49:30.343] Search Brave History[Script Filter] Queuing argument 'test'
[12:49:32.644] Search Brave History[Script Filter] Queuing argument 'test'
[12:49:32.770] Search Brave History[Script Filter] Script with argv 'test' finished
[12:49:32.772] ERROR: Search Brave History[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.4E11D985-1334-4820-AF95-B8F25D21267E/brave_bookmarks.py", line 53, in <module>
    bookmarks = get_all_urls(bm_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.4E11D985-1334-4820-AF95-B8F25D21267E/brave_bookmarks.py", line 29, in get_all_urls
    get_container(the_json)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.4E11D985-1334-4820-AF95-B8F25D21267E/brave_bookmarks.py", line 27, in get_container
    extract_data(i)
  File "/Users/path/to/alfred/Alfred.alfredpreferences/workflows/user.workflow.4E11D985-1334-4820-AF95-B8F25D21267E/brave_bookmarks.py", line 15, in extract_data
    if data.get('type') == 'url':
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by Acidham** [comment]
Arg, as mentioned I cannot reproduce. Would it be possible to share the Bookmarks file with me? You can find it under ~/Library/Application Support/BraveSoftware/Brave-Browser/Default/

If you don't want to share it here you can send it to me via acidham@gmail.com

**Comment by Acidham** [comment]
@ThomasBormans I started to implement a new version which supports more browsers not just brave: https://github.com/Acidham/chromium-hist-bookmarks and I was able to reproduce the Unicode error. I committed the last version of this workflow and will continue to maintain a more comprehensive solution: https://github.com/Acidham/chromium-hist-bookmarks.

Let me know if the issue is fixed finally.

**Comment by ThomasBormans** [comment]
@Acidham I tried the other workflow and this works perfectly. Thanks for the new package and the quick updates!
